MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.ResNet50_conv5_body_fpt
  FASTER_RCNN: True
NUM_GPUS: 8
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/resnet50_caffe.pth'
  # IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/R-50-GN.pkl'
  
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.05
  GAMMA: 0.1
  MAX_ITER: 120000
  STEPS: [0, 80000, 100000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  USE_GN: True

FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head_gn_fptnet
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  SCALES: (1200,1200,1000,800,600,400)
  MAX_SIZE: 1400
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000
TEST:
  SCALE: 1000
  MAX_SIZE: 1400
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000
  RPN_POST_NMS_TOP_N: 1000
